# Generated by Django 4.1.2 on 2022-10-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_api', '0003_blood_donation_blood_group_userprofile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blood_choices',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
