# Generated by Django 4.1.2 on 2022-10-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_api', '0004_category_blood_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_choices', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='blood_choices',
        ),
        migrations.AlterField(
            model_name='blood_donation',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_api.blood_choice'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_api.blood_choice'),
        ),
    ]
