# Generated by Django 4.1.2 on 2022-10-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_api', '0005_blood_choice_remove_category_blood_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
