# Generated by Django 4.1.2 on 2022-10-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_api', '0006_remove_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
    ]
